export enum PermissionGroupEnum {
  LABOR_RISK = 'LABOR_RISK',
  PRODUCT_TRACING = 'PRODUCT_TRACING',
  OTHERS = 'OTHERS',
}

export enum ProductTypeEnum {
  LOG_PURCHASES = 'purchaseFrom',
  LOG_SALE = 'sellTo',
}

export enum PermissionActionEnum {
  ONBOARDING = 'ONBOARDING',
  COMPLETE_OWN_PROFILE = 'COMPLETE_OWN_PROFILE',
  ONBOARD_OWN_ACCOUNT = 'ONBOARD_OWN_ACCOUNT',
  ONBOARDING_ADMIN = 'ONBOARDING_ADMIN',

  INVITE_PARTNERS = 'INVITE_PARTNERS',

  LOG_PURCHASE = 'LOG_PURCHASE',
  INPUT_PRODUCT_ID_IN_PURCHASE = 'INPUT_PRODUCT_ID_IN_PURCHASE',
  INPUT_PRODUCT_ID_IN_SALE = 'INPUT_PRODUCT_ID_IN_SALE',
  INPUT_PRODUCT_ID_IN_TRANSPORT = 'INPUT_PRODUCT_ID_IN_TRANSPORT',
  SCAN_QR_CODE_IN_PURCHASE = 'SCAN_QR_CODE_IN_PURCHASE',
  SCAN_QR_CODE_IN_SALE = 'SCAN_QR_CODE_IN_SALE',
  SCAN_QR_CODE_IN_TRANSPORT = 'SCAN_QR_CODE_IN_TRANSPORT',
  MANUALLY_DEFINE_NEW_PRODUCT = 'MANUALLY_DEFINE_NEW_PRODUCT',
  ALLOW_PURCHASE_INTERMEDIARIES = 'ALLOW_PURCHASE_INTERMEDIARIES',

  LOG_TRANSFORMATIONS = 'LOG_TRANSFORMATIONS',
  ASSIGN_PRODUCT_ID = 'ASSIGN_PRODUCT_ID',
  ASSIGN_QR_CODE = 'ASSIGN_QR_CODE',
  ASSIGN_DNA = 'ASSIGN_DNA',

  LOG_SALE = 'LOG_SALE',
  ALLOW_SALE_INTERMEDIARIES = 'ALLOW_SALE_INTERMEDIARIES',

  LOG_BY_PRODUCT = 'LOG_BY_PRODUCT',

  LOG_TRANSPORT = 'LOG_TRANSPORT',

  VIEW_HISTORY = 'VIEW_HISTORY',

  SUBMIT_REPORTS = 'SUBMIT_REPORTS',
  PROACTIVE_ASSESSMENTS = 'PROACTIVE_ASSESSMENTS',
  REACTIVE_ASSESSMENTS = 'REACTIVE_ASSESSMENTS',

  VIEW_REPORTS = 'VIEW_REPORTS',
  VIEW_ONLY_MY_REPORTS = 'VIEW_ONLY_MY_REPORTS',
  VIEW_ALL_REPORTS = 'VIEW_ALL_REPORTS',

  DNA = 'DNA',
  VIEW_DNA_TEST_RESULTS = 'VIEW_DNA_TEST_RESULTS',
  LOG_DNA_TEST_RESULTS = 'LOG_DNA_TEST_RESULTS',

  GENERATE_QR_CODES = 'GENERATE_QR_CODES',

  SUBMIT_ASSESSMENTS = 'SUBMIT_ASSESSMENTS',
  REFER_REPORT_FOR_FOLLOW_UP = 'REFER_REPORT_FOR_FOLLOW_UP',

  USER_MANAGEMENT = 'USER_MANAGEMENT',
  VIEW_SUPPLIER_RISK_ASSESSMENT = 'VIEW_SUPPLIER_RISK_ASSESSMENT',

  TRACE_PRODUCT = 'TRACE_PRODUCT',

  SUPPLIER_MANAGEMENT = 'SUPPLIER_MANAGEMENT',
  COMPLETE_OWN_SAQ = 'COMPLETE_OWN_SAQ',
  NO_SAQ = 'NO_SAQ',
  VIEW_MARGIN_OF_ERROR = 'VIEW_MARGIN_OF_ERROR',
  VIEW_SUPPLIER_RISK_ASSESSMENT_IN_SUPPLIER_MANAGEMENT = 'VIEW_SUPPLIER_RISK_ASSESSMENT_IN_SUPPLIER_MANAGEMENT',
  VIEW_SUPPLIER_RISK_ASSESSMENT_IN_USER_MANAGEMENT = 'VIEW_SUPPLIER_RISK_ASSESSMENT_IN_USER_MANAGEMENT',
}

export enum ChainOfCustodyEnum {
  PRODUCT_SEGREGATION = 'Product Segregation',
  MASS_BALANCE = 'Mass balance',
}

export enum RoleTypeEnum {
  PRODUCT = 'Product',
  LABOR = 'Labor',
  ADMINISTRATOR = 'Administrator',
  BRAND = 'Brand',
}

export enum GroupTypeEnum {
  RADIO_MULTIPLE_GROUP = 'RADIO_MULTIPLE_GROUP',
  CHECKBOX_GROUP = 'CHECKBOX_GROUP',
  CHECKBOX = 'CHECKBOX',
  RADIO_GROUP = 'RADIO_GROUP',
}
