export enum SettingTabEnum {
  SETUP_PROFILE = 'SETUP_PROFILE',
  ADD_PRODUCT = 'ADD_PRODUCT',
  ROLE_PERMISSION = 'ROLE_PERMISSION',
  SUPPLY_CHAIN_MAPPING = 'SUPPLY_CHAIN_MAPPING',
  TAXONOMY_OF_EXPLOITATION = 'TAXONOMY_OF_EXPLOITATION',
  CONFIGURABLE_SAQ = 'CONFIGURABLE_SAQ',
  RISK_ASSESSMENT = 'RISK_ASSESSMENT',
  PREVIEW = 'PREVIEW',
}
