/* eslint-disable max-lines */
export default [
  {
    id: '54cf96ac-fc25-4ced-b66b-19db580d5c82',
    name: 'hbhb',
    riskData: {
      data: [
        {
          risk: {
            level: 'High',
            score: 7.513614457831325,
          },
          category: {
            id: '92301b80-3cfa-497d-bba8-1e2facd55778',
            icon: 'Gender equality',
            name: 'Due Diligence Management System',
            type: 3,
            urls: null,
            parentId: null,
            createdAt: 1711596523,
            deletedAt: null,
            updatedAt: 1713239959,
            categoryId: null,
            description: null,
            translation: {
              en: 'Due Diligence Management System',
              ur: 'ڈیو ڈیلیجنس مینجمنٹ سسٹم',
            },
            riskSeverity: 1,
          },
          sourceRiskData: [
            {
              risk: {
                level: 'High',
                score: 9,
              },
              source: 'AUDITOR',
            },
            {
              risk: {
                level: 'Medium',
                score: 7.5,
              },
              source: 'Admin',
            },
            {
              risk: {
                level: 'Medium',
                score: 5.63,
              },
              source: 'CAP',
            },
          ],
          indicatorRiskData: [
            {
              risk: {
                level: 'Extreme',
                score: 12,
              },
              indicator: {
                id: '0a8fbf6e-18e7-4f2d-ac53-89195719c2c7',
                icon: null,
                name: 'Audit',
                type: 1,
                urls: null,
                category: {
                  id: '92301b80-3cfa-497d-bba8-1e2facd55778',
                  icon: 'Gender equality',
                  name: 'Due Diligence Management System',
                  type: 3,
                  urls: null,
                  parentId: null,
                  createdAt: 1711596523,
                  deletedAt: null,
                  updatedAt: 1713239959,
                  categoryId: null,
                  description: null,
                  translation: {
                    en: 'Due Diligence Management System',
                    ur: 'ڈیو ڈیلیجنس مینجمنٹ سسٹم',
                  },
                  riskSeverity: 1,
                },
                parentId: null,
                createdAt: 1711596523,
                deletedAt: null,
                updatedAt: 1714016298,
                categoryId: '92301b80-3cfa-497d-bba8-1e2facd55778',
                description: null,
                translation: {
                  en: 'Audit',
                  ur: 'Audit urdu',
                },
                riskSeverity: 1,
              },
              subIndicatorRiskData: [
                {
                  data: [
                    {
                      note: 'Corrective Action Plan assigned by thuy phan',
                      risk: {
                        level: 'No weight',
                        score: 0,
                      },
                      capId: 'e6c09149-bbb2-4900-8d38-95847f9216c6',
                      roleId: null,
                      source: 'CAP',
                      createdAt: 1719566941,
                      isIndirect: false,
                    },
                    {
                      note: 'Corrective Action Plan assigned by thuy abcd brand',
                      risk: {
                        level: 'No weight',
                        score: 0,
                      },
                      capId: 'd77e3492-1a05-4686-bb5b-817053ff485b',
                      roleId: null,
                      source: 'CAP',
                      createdAt: 1719566203,
                      isIndirect: false,
                    },
                    {
                      note: 'Corrective Action Plan assigned by thuy abcd brand',
                      risk: {
                        level: 'No weight',
                        score: 0,
                      },
                      capId: '7f63340e-f1c0-4dbc-a46d-6f87679f1ae2',
                      roleId: null,
                      source: 'CAP',
                      createdAt: 1719482699,
                      isIndirect: false,
                    },
                    {
                      note: 'Corrective Action Plan assigned by thuy phan',
                      risk: {
                        level: 'No weight',
                        score: 0,
                      },
                      capId: '45eca910-a2fe-443a-954b-0c750480214d',
                      roleId: null,
                      source: 'CAP',
                      createdAt: 1719481566,
                      isIndirect: false,
                    },
                    {
                      note: 'Corrective Action Plan assigned by thuy phan',
                      risk: {
                        level: 'No weight',
                        score: 0,
                      },
                      capId: '411cf6f9-3052-4a81-991c-cb1748a2325c',
                      roleId: null,
                      source: 'CAP',
                      createdAt: 1719387257,
                      isIndirect: false,
                    },
                    {
                      note: 'thuy assign report',
                      risk: {
                        level: 'Extreme',
                        score: 12,
                      },
                      roleId: null,
                      source: 'Admin',
                      createdAt: 1717037585,
                      isIndirect: false,
                    },
                    {
                      note: 'aaa',
                      risk: {
                        level: 'Extreme',
                        score: 12,
                      },
                      roleId: null,
                      source: 'Admin',
                      createdAt: 1711618010,
                      isIndirect: false,
                    },
                    {
                      note: 'aaaa',
                      risk: {
                        level: 'Extreme',
                        score: 12,
                      },
                      roleId: null,
                      source: 'Admin',
                      createdAt: 1711617577,
                      isIndirect: false,
                    },
                  ],
                  risk: {
                    level: 'Extreme',
                    score: 12,
                  },
                  subIndicator: {
                    id: '7e382558-6cf0-48fd-a4a2-7fba44d0a7f4',
                    icon: null,
                    name: 'Missing audit',
                    type: 2,
                    urls: null,
                    parentId: '0a8fbf6e-18e7-4f2d-ac53-89195719c2c7',
                    createdAt: 1711596523,
                    deletedAt: null,
                    updatedAt: 1714016298,
                    categoryId: '92301b80-3cfa-497d-bba8-1e2facd55778',
                    description: null,
                    translation: {
                      en: 'Missing audit',
                      ur: 'Missing audit urdu',
                    },
                    riskSeverity: 4,
                  },
                },
              ],
            },
            {
              risk: {
                level: 'Extreme',
                score: 12,
              },
              indicator: {
                id: 'db86365b-d752-4eec-9c9c-922a2ed3d429',
                icon: null,
                name: 'OECD Guidance for RBC',
                type: 1,
                urls: null,
                category: {
                  id: '92301b80-3cfa-497d-bba8-1e2facd55778',
                  icon: 'Gender equality',
                  name: 'Due Diligence Management System',
                  type: 3,
                  urls: null,
                  parentId: null,
                  createdAt: 1711596523,
                  deletedAt: null,
                  updatedAt: 1713239959,
                  categoryId: null,
                  description: null,
                  translation: {
                    en: 'Due Diligence Management System',
                    ur: 'ڈیو ڈیلیجنس مینجمنٹ سسٹم',
                  },
                  riskSeverity: 1,
                },
                parentId: null,
                createdAt: 1711596523,
                deletedAt: null,
                updatedAt: 1711596523,
                categoryId: '92301b80-3cfa-497d-bba8-1e2facd55778',
                description: null,
                translation: {
                  en: 'OECD Guidance for RBC',
                },
                riskSeverity: 1,
              },
              subIndicatorRiskData: [
                {
                  data: [
                    {
                      note: 'thuy abcd',
                      risk: {
                        level: 'Extreme',
                        score: 12,
                      },
                      roleId: null,
                      source: 'Admin',
                      createdAt: 1719453442,
                      isIndirect: false,
                    },
                  ],
                  risk: {
                    level: 'Extreme',
                    score: 12,
                  },
                  subIndicator: {
                    id: 'd5e80e4e-17b6-44df-8d3f-354cf7cec457',
                    icon: null,
                    name: 'Inadequate Implementaion of Step 1. Embed responsible business conduct in enterprise policy and management systems',
                    type: 2,
                    urls: null,
                    parentId: 'db86365b-d752-4eec-9c9c-922a2ed3d429',
                    createdAt: 1711596523,
                    deletedAt: null,
                    updatedAt: 1711596523,
                    categoryId: '92301b80-3cfa-497d-bba8-1e2facd55778',
                    description: null,
                    translation: {
                      en: 'Inadequate Implementaion of Step 1. Embed responsible business conduct in enterprise policy and management systems',
                    },
                    riskSeverity: 4,
                  },
                },
              ],
            },
            {
              risk: {
                level: 'High',
                score: 9,
              },
              indicator: {
                id: 'e0415a83-2665-442e-8d39-b7fa29051389',
                icon: null,
                name: 'Supplier procedures',
                type: 1,
                urls: null,
                category: {
                  id: '92301b80-3cfa-497d-bba8-1e2facd55778',
                  icon: 'Gender equality',
                  name: 'Due Diligence Management System',
                  type: 3,
                  urls: null,
                  parentId: null,
                  createdAt: 1711596523,
                  deletedAt: null,
                  updatedAt: 1713239959,
                  categoryId: null,
                  description: null,
                  translation: {
                    en: 'Due Diligence Management System',
                    ur: 'ڈیو ڈیلیجنس مینجمنٹ سسٹم',
                  },
                  riskSeverity: 1,
                },
                parentId: null,
                createdAt: 1711596523,
                deletedAt: null,
                updatedAt: 1711596523,
                categoryId: '92301b80-3cfa-497d-bba8-1e2facd55778',
                description: null,
                translation: {
                  en: 'Supplier procedures',
                },
                riskSeverity: 1,
              },
              subIndicatorRiskData: [
                {
                  data: [
                    {
                      note: 'thuy 13.5',
                      risk: {
                        level: 'High',
                        score: 9,
                      },
                      roleId: '62660fc3-4b32-4e7d-b487-59b83b3ad973',
                      source: 'AUDITOR',
                      createdAt: 1715590569,
                      isIndirect: false,
                    },
                  ],
                  risk: {
                    level: 'High',
                    score: 9,
                  },
                  subIndicator: {
                    id: '2aa37e53-2192-4105-9ad0-80dc6bcfabad',
                    icon: null,
                    name: 'Incomplete policy of disclosing sub-contractors',
                    type: 2,
                    urls: null,
                    parentId: 'e0415a83-2665-442e-8d39-b7fa29051389',
                    createdAt: 1711596523,
                    deletedAt: null,
                    updatedAt: 1711596523,
                    categoryId: '92301b80-3cfa-497d-bba8-1e2facd55778',
                    description: null,
                    translation: {
                      en: 'Incomplete policy of disclosing sub-contractors',
                    },
                    riskSeverity: 3,
                  },
                },
              ],
            },
            {
              risk: {
                level: 'Medium',
                score: 5.63,
              },
              indicator: {
                id: 'f6d903a1-8e15-4366-9bf5-ac2ee1d8cc34',
                icon: null,
                name: 'Product Testing',
                type: 1,
                urls: null,
                category: {
                  id: '92301b80-3cfa-497d-bba8-1e2facd55778',
                  icon: 'Gender equality',
                  name: 'Due Diligence Management System',
                  type: 3,
                  urls: null,
                  parentId: null,
                  createdAt: 1711596523,
                  deletedAt: null,
                  updatedAt: 1713239959,
                  categoryId: null,
                  description: null,
                  translation: {
                    en: 'Due Diligence Management System',
                    ur: 'ڈیو ڈیلیجنس مینجمنٹ سسٹم',
                  },
                  riskSeverity: 1,
                },
                parentId: null,
                createdAt: 1711596523,
                deletedAt: null,
                updatedAt: 1713340584,
                categoryId: '92301b80-3cfa-497d-bba8-1e2facd55778',
                description: null,
                translation: {
                  en: 'Product Testing',
                  ur: 'مصنوعات کی جانچ',
                },
                riskSeverity: 1,
              },
              subIndicatorRiskData: [
                {
                  data: [
                    {
                      note: 'Evidence accepted of completion of corrective actions.<strong> New risk level assigned: Medium risk </strong>',
                      risk: {
                        level: 'Medium',
                        score: 5.63,
                      },
                      capId: '0b1594da-bede-4580-a7e4-5cda5b49af21',
                      roleId: null,
                      source: 'CAP',
                      createdAt: 1719484361,
                      isIndirect: false,
                    },
                    {
                      note: 'Corrective Action Plan assigned by thuy abcd brand',
                      risk: {
                        level: 'No weight',
                        score: 0,
                      },
                      capId: '4df0cb0b-7574-488c-8a2e-978d4c2fa75f',
                      roleId: null,
                      source: 'CAP',
                      createdAt: 1719483910,
                      isIndirect: false,
                    },
                    {
                      note: 'assign report after CAP nôttototo resolved',
                      risk: {
                        level: 'Medium',
                        score: 5,
                      },
                      roleId: null,
                      source: 'Admin',
                      createdAt: 1717038115,
                      isIndirect: false,
                    },
                    {
                      note: 'thuy add report after cap resolved',
                      risk: {
                        level: 'Medium',
                        score: 5,
                      },
                      roleId: null,
                      source: 'Admin',
                      createdAt: 1715831836,
                      isIndirect: false,
                    },
                    {
                      note: 'aaaa',
                      risk: {
                        level: 'Medium',
                        score: 5,
                      },
                      roleId: null,
                      source: 'Admin',
                      createdAt: 1715831517,
                      isIndirect: false,
                    },
                    {
                      note: null,
                      risk: {
                        level: 'Medium',
                        score: 5,
                      },
                      roleId: null,
                      source: 'DNA test results',
                      createdAt: 1714621533,
                    },
                    {
                      note: null,
                      risk: {
                        level: 'Extreme',
                        score: 15,
                      },
                      roleId: null,
                      source: 'DNA test results',
                      createdAt: 1714621344,
                    },
                    {
                      note: null,
                      risk: {
                        level: 'Extreme',
                        score: 15,
                      },
                      roleId: null,
                      source: 'DNA test results',
                      createdAt: 1714621286,
                    },
                    {
                      note: null,
                      risk: {
                        level: 'Extreme',
                        score: 15,
                      },
                      roleId: null,
                      source: 'DNA test results',
                      createdAt: 1714620711,
                    },
                    {
                      note: null,
                      risk: {
                        level: 'Extreme',
                        score: 15,
                      },
                      roleId: null,
                      source: 'DNA test results',
                      createdAt: 1706154906,
                    },
                    {
                      note: null,
                      risk: {
                        level: 'Medium',
                        score: 5,
                      },
                      roleId: null,
                      source: 'DNA test results',
                      createdAt: 1706088772,
                    },
                    {
                      note: null,
                      risk: {
                        level: 'Extreme',
                        score: 15,
                      },
                      roleId: null,
                      source: 'DNA test results',
                      createdAt: 1705484494,
                    },
                    {
                      note: null,
                      risk: {
                        level: 'Extreme',
                        score: 15,
                      },
                      roleId: null,
                      source: 'DNA test results',
                      createdAt: 1705378448,
                    },
                    {
                      note: null,
                      risk: {
                        level: 'Extreme',
                        score: 15,
                      },
                      roleId: null,
                      source: 'DNA test results',
                      createdAt: 1704961306,
                    },
                    {
                      note: null,
                      risk: {
                        level: 'Medium',
                        score: 5,
                      },
                      roleId: null,
                      source: 'DNA test results',
                      createdAt: 1704943978,
                    },
                    {
                      note: null,
                      risk: {
                        level: 'Extreme',
                        score: 15,
                      },
                      roleId: null,
                      source: 'DNA test results',
                      createdAt: 1704943590,
                    },
                    {
                      note: null,
                      risk: {
                        level: 'Medium',
                        score: 5,
                      },
                      roleId: null,
                      source: 'DNA test results',
                      createdAt: 1704882515,
                    },
                    {
                      note: null,
                      risk: {
                        level: 'Extreme',
                        score: 15,
                      },
                      roleId: null,
                      source: 'DNA test results',
                      createdAt: 1702546459,
                    },
                    {
                      note: null,
                      risk: {
                        level: 'Extreme',
                        score: 15,
                      },
                      roleId: null,
                      source: 'DNA test results',
                      createdAt: 1692333778,
                    },
                  ],
                  risk: {
                    level: 'Medium',
                    score: 5.63,
                  },
                  subIndicator: {
                    id: 'b74ae455-bd32-4b29-9cda-e478eef8a473',
                    icon: null,
                    name: 'Failed DNA Test',
                    type: 2,
                    urls: null,
                    parentId: 'f6d903a1-8e15-4366-9bf5-ac2ee1d8cc34',
                    createdAt: 1711596523,
                    deletedAt: null,
                    updatedAt: 1713239959,
                    categoryId: '92301b80-3cfa-497d-bba8-1e2facd55778',
                    description: null,
                    translation: {
                      en: 'Failed DNA Test',
                      ur: 'Failed DNA Test Urdu',
                    },
                    riskSeverity: 5,
                  },
                },
              ],
            },
            {
              risk: {
                level: 'Low',
                score: 3,
              },
              indicator: {
                id: 'f2516347-7a15-4082-8977-09ba3ae60373',
                icon: null,
                name: 'Product Documentation',
                type: 1,
                urls: null,
                category: {
                  id: '92301b80-3cfa-497d-bba8-1e2facd55778',
                  icon: 'Gender equality',
                  name: 'Due Diligence Management System',
                  type: 3,
                  urls: null,
                  parentId: null,
                  createdAt: 1711596523,
                  deletedAt: null,
                  updatedAt: 1713239959,
                  categoryId: null,
                  description: null,
                  translation: {
                    en: 'Due Diligence Management System',
                    ur: 'ڈیو ڈیلیجنس مینجمنٹ سسٹم',
                  },
                  riskSeverity: 1,
                },
                parentId: null,
                createdAt: 1711596523,
                deletedAt: null,
                updatedAt: 1713340854,
                categoryId: '92301b80-3cfa-497d-bba8-1e2facd55778',
                description: null,
                translation: {
                  en: 'Product Documentation',
                  ur: 'پروڈکٹ کی دستاویزات',
                },
                riskSeverity: 1,
              },
              subIndicatorRiskData: [
                {
                  data: [
                    {
                      note: 'Corrective Action Plan assigned by thuy abcd brand',
                      risk: {
                        level: 'No weight',
                        score: 0,
                      },
                      capId: '4c0853ba-a5ca-4f69-a591-207760dfb68a',
                      roleId: null,
                      source: 'CAP',
                      createdAt: 1719545772,
                      isIndirect: false,
                    },
                    {
                      note: 'Corrective Action Plan assigned by thuy abcd brand',
                      risk: {
                        level: 'No weight',
                        score: 0,
                      },
                      capId: 'e64332e2-12b6-45cc-b08d-ef9682bb67cc',
                      roleId: null,
                      source: 'CAP',
                      createdAt: 1719484577,
                      isIndirect: false,
                    },
                    {
                      note: 'thuy add 3',
                      risk: {
                        level: 'Low',
                        score: 3,
                      },
                      roleId: null,
                      source: 'Admin',
                      createdAt: 1717065893,
                      isIndirect: false,
                    },
                    {
                      note: 'thuy add2',
                      risk: {
                        level: 'Low',
                        score: 3,
                      },
                      roleId: null,
                      source: 'Admin',
                      createdAt: 1717065731,
                      isIndirect: false,
                    },
                    {
                      note: 'thuy add',
                      risk: {
                        level: 'Low',
                        score: 3,
                      },
                      roleId: null,
                      source: 'Admin',
                      createdAt: 1717065534,
                      isIndirect: false,
                    },
                    {
                      note: 'aaa',
                      risk: {
                        level: 'Low',
                        score: 3,
                      },
                      roleId: null,
                      source: 'Admin',
                      createdAt: 1711618010,
                      isIndirect: false,
                    },
                  ],
                  risk: {
                    level: 'Low',
                    score: 3,
                  },
                  subIndicator: {
                    id: 'ca03a144-1470-4e79-911e-02a08721015d',
                    icon: null,
                    name: 'Incomplete documentation on product origin',
                    type: 2,
                    urls: null,
                    parentId: 'f2516347-7a15-4082-8977-09ba3ae60373',
                    createdAt: 1711596523,
                    deletedAt: null,
                    updatedAt: 1713495761,
                    categoryId: '92301b80-3cfa-497d-bba8-1e2facd55778',
                    description: null,
                    translation: {
                      en: 'Incomplete documentation on product origin',
                      ur: 'پروڈکٹ کے اصل مقام کی نامکمل دستاویزات',
                    },
                    riskSeverity: 1,
                  },
                },
              ],
            },
          ],
        },
        {
          risk: {
            level: 'High',
            score: 7.8,
          },
          category: {
            id: 'ee377735-7174-4518-9159-d13cb8fe2ffd',
            icon: 'Warning',
            name: 'Freedom of Association',
            type: 3,
            urls: null,
            parentId: null,
            createdAt: 1711596523,
            deletedAt: null,
            updatedAt: 1713239959,
            categoryId: null,
            description: null,
            translation: {
              en: 'Freedom of Association',
              ur: 'Freedom of Association urdu',
            },
            riskSeverity: 1,
          },
          sourceRiskData: [
            {
              risk: {
                level: 'High',
                score: 9,
              },
              source: 'Admin',
            },
            {
              risk: {
                level: 'Low',
                score: 3,
              },
              source: 'Product risk listings',
            },
          ],
          indicatorRiskData: [
            {
              risk: {
                level: 'High',
                score: 7.8,
              },
              indicator: {
                id: '520d7afa-06e3-475b-a573-fc6f0e43bdbf',
                icon: null,
                name: 'Collective bargaining',
                type: 1,
                urls: null,
                category: {
                  id: 'ee377735-7174-4518-9159-d13cb8fe2ffd',
                  icon: 'Warning',
                  name: 'Freedom of Association',
                  type: 3,
                  urls: null,
                  parentId: null,
                  createdAt: 1711596523,
                  deletedAt: null,
                  updatedAt: 1713239959,
                  categoryId: null,
                  description: null,
                  translation: {
                    en: 'Freedom of Association',
                    ur: 'Freedom of Association urdu',
                  },
                  riskSeverity: 1,
                },
                parentId: null,
                createdAt: 1711596523,
                deletedAt: null,
                updatedAt: 1713239959,
                categoryId: 'ee377735-7174-4518-9159-d13cb8fe2ffd',
                description: null,
                translation: {
                  en: 'Collective bargaining',
                  ur: 'اجتمائی سودے بازی',
                },
                riskSeverity: 1,
              },
              subIndicatorRiskData: [
                {
                  data: [
                    {
                      note: 'Corrective Action Plan assigned by thuy abcd brand',
                      risk: {
                        level: 'No weight',
                        score: 0,
                      },
                      capId: '9c1864be-bb8c-4358-a4bd-710c5baed99f',
                      roleId: null,
                      source: 'CAP',
                      createdAt: 1719561015,
                      isIndirect: false,
                    },
                    {
                      note: 'aaa',
                      risk: {
                        level: 'High',
                        score: 9,
                      },
                      roleId: null,
                      source: 'Admin',
                      createdAt: 1711618010,
                      isIndirect: false,
                    },
                    {
                      note: 'aaaa',
                      risk: {
                        level: 'High',
                        score: 9,
                      },
                      roleId: null,
                      source: 'Admin',
                      createdAt: 1711617577,
                      isIndirect: false,
                    },
                    {
                      note: 'Gloves',
                      risk: {
                        level: 'Low',
                        score: 3,
                      },
                      roleId: null,
                      source: 'Product risk listings',
                      createdAt: 1662687784,
                    },
                  ],
                  risk: {
                    level: 'High',
                    score: 7.8,
                  },
                  subIndicator: {
                    id: '424f4c5e-32b6-4b8e-9083-cf31d4738bbd',
                    icon: null,
                    name: 'Collective bargaining agreements not in effect in the enterprise',
                    type: 2,
                    urls: null,
                    parentId: '520d7afa-06e3-475b-a573-fc6f0e43bdbf',
                    createdAt: 1711596523,
                    deletedAt: null,
                    updatedAt: 1713239959,
                    categoryId: 'ee377735-7174-4518-9159-d13cb8fe2ffd',
                    description: null,
                    translation: {
                      en: 'Collective bargaining agreements not in effect in the enterprise',
                      ur: 'اجتماعی سودے بازی کے معاہدے انٹرپرائز میں نافذ العمل نہیں ہیں۔',
                    },
                    riskSeverity: 3,
                  },
                },
              ],
            },
          ],
        },
        {
          risk: {
            level: 'High',
            score: 8.377166666666666,
          },
          category: {
            id: 'd716e43e-7eb7-48c4-a475-98a7cbbdc830',
            icon: 'Abusive working and living conditions',
            name: 'Labor',
            type: 3,
            urls: null,
            parentId: null,
            createdAt: 1711596523,
            deletedAt: null,
            updatedAt: 1718853151,
            categoryId: null,
            description: null,
            translation: {
              en: 'Labor',
            },
            riskSeverity: 1,
          },
          sourceRiskData: [
            {
              risk: {
                level: 'High',
                score: 8.8,
              },
              source: 'Admin',
            },
            {
              risk: {
                level: 'High',
                score: 10.5,
              },
              source: 'AUDITOR',
            },
            {
              risk: {
                level: 'Medium',
                score: 5.63,
              },
              source: 'CAP',
            },
            {
              risk: {
                level: 'Low',
                score: 3,
              },
              source: 'Product risk listings',
            },
          ],
          indicatorRiskData: [
            {
              risk: {
                level: 'Extreme',
                score: 12,
              },
              indicator: {
                id: 'f1d05f79-5485-4137-933b-44709a7c6de0',
                icon: null,
                name: 'Excessive Overtime',
                type: 1,
                urls: null,
                category: {
                  id: 'd716e43e-7eb7-48c4-a475-98a7cbbdc830',
                  icon: 'Abusive working and living conditions',
                  name: 'Labor',
                  type: 3,
                  urls: null,
                  parentId: null,
                  createdAt: 1711596523,
                  deletedAt: null,
                  updatedAt: 1718853151,
                  categoryId: null,
                  description: null,
                  translation: {
                    en: 'Labor',
                  },
                  riskSeverity: 1,
                },
                parentId: null,
                createdAt: 1711596523,
                deletedAt: null,
                updatedAt: 1718792307,
                categoryId: 'd716e43e-7eb7-48c4-a475-98a7cbbdc830',
                description: null,
                translation: {
                  en: 'Excessive Overtime',
                },
                riskSeverity: 1,
              },
              subIndicatorRiskData: [
                {
                  data: [
                    {
                      note: 'Corrective Action Plan assigned by thuy phan',
                      risk: {
                        level: 'No weight',
                        score: 0,
                      },
                      capId: 'afdbf902-019b-4ee9-a52a-7a36931d440f',
                      roleId: null,
                      source: 'CAP',
                      createdAt: 1718332973,
                      isIndirect: false,
                    },
                    {
                      note: 'thuy add report 7.5',
                      risk: {
                        level: 'Extreme',
                        score: 12,
                      },
                      roleId: null,
                      source: 'Admin',
                      createdAt: 1715057808,
                      isIndirect: false,
                    },
                  ],
                  risk: {
                    level: 'Extreme',
                    score: 12,
                  },
                  subIndicator: {
                    id: '4f7b4292-4ef8-4f26-8991-68c38e8c0a27',
                    icon: null,
                    name: 'Forced to work on call (day and night)',
                    type: 2,
                    urls: null,
                    parentId: 'f1d05f79-5485-4137-933b-44709a7c6de0',
                    createdAt: 1711596523,
                    deletedAt: null,
                    updatedAt: 1718792307,
                    categoryId: 'd716e43e-7eb7-48c4-a475-98a7cbbdc830',
                    description: null,
                    translation: {
                      en: 'Forced to work on call (day and night)',
                      ur: 'زبردستی کام کیلئے بلانا (دن اور رات) میں',
                    },
                    riskSeverity: 4,
                  },
                },
              ],
            },
            {
              risk: {
                level: 'Extreme',
                score: 12,
              },
              indicator: {
                id: '4298885b-c05f-43c9-b817-cfe0e247664a',
                icon: null,
                name: 'Withholding wages',
                type: 1,
                urls: null,
                category: {
                  id: 'd716e43e-7eb7-48c4-a475-98a7cbbdc830',
                  icon: 'Abusive working and living conditions',
                  name: 'Labor',
                  type: 3,
                  urls: null,
                  parentId: null,
                  createdAt: 1711596523,
                  deletedAt: null,
                  updatedAt: 1718853151,
                  categoryId: null,
                  description: null,
                  translation: {
                    en: 'Labor',
                  },
                  riskSeverity: 1,
                },
                parentId: null,
                createdAt: 1711596523,
                deletedAt: null,
                updatedAt: 1718792307,
                categoryId: 'd716e43e-7eb7-48c4-a475-98a7cbbdc830',
                description: null,
                translation: {
                  en: 'Withholding wages',
                },
                riskSeverity: 1,
              },
              subIndicatorRiskData: [
                {
                  data: [
                    {
                      note: 'thuy 13.5',
                      risk: {
                        level: 'Extreme',
                        score: 12,
                      },
                      roleId: '62660fc3-4b32-4e7d-b487-59b83b3ad973',
                      source: 'AUDITOR',
                      createdAt: 1715590569,
                      isIndirect: false,
                    },
                  ],
                  risk: {
                    level: 'Extreme',
                    score: 12,
                  },
                  subIndicator: {
                    id: '83c97b50-aba3-4a3c-b98c-ba7908cc7030',
                    icon: null,
                    name: 'Late payment of wages (after work is completed)',
                    type: 2,
                    urls: null,
                    parentId: '4298885b-c05f-43c9-b817-cfe0e247664a',
                    createdAt: 1711596523,
                    deletedAt: null,
                    updatedAt: 1718792307,
                    categoryId: 'd716e43e-7eb7-48c4-a475-98a7cbbdc830',
                    description: null,
                    translation: {
                      en: 'Late payment of wages (after work is completed)',
                    },
                    riskSeverity: 4,
                  },
                },
              ],
            },
            {
              risk: {
                level: 'High',
                score: 9.3125,
              },
              indicator: {
                id: '76d03cd3-c5f2-450e-8280-63ee89877835',
                icon: null,
                name: 'Abusive working and living conditions',
                type: 1,
                urls: null,
                category: {
                  id: 'd716e43e-7eb7-48c4-a475-98a7cbbdc830',
                  icon: 'Abusive working and living conditions',
                  name: 'Labor',
                  type: 3,
                  urls: null,
                  parentId: null,
                  createdAt: 1711596523,
                  deletedAt: null,
                  updatedAt: 1718853151,
                  categoryId: null,
                  description: null,
                  translation: {
                    en: 'Labor',
                  },
                  riskSeverity: 1,
                },
                parentId: null,
                createdAt: 1711596523,
                deletedAt: null,
                updatedAt: 1718792307,
                categoryId: 'd716e43e-7eb7-48c4-a475-98a7cbbdc830',
                description: null,
                translation: {
                  en: 'Abusive working and living conditions',
                  ur: 'Abusive working and living conditions urdu',
                },
                riskSeverity: 1,
              },
              subIndicatorRiskData: [
                {
                  data: [
                    {
                      note: 'adasdasd',
                      risk: {
                        level: 'High',
                        score: 9,
                      },
                      roleId: null,
                      source: 'Admin',
                      createdAt: 1718081233,
                      isIndirect: false,
                    },
                  ],
                  risk: {
                    level: 'High',
                    score: 9,
                  },
                  subIndicator: {
                    id: '1bc90678-423f-49e6-9b3e-24d68205313d',
                    icon: null,
                    name: 'Accommodation does not comply with health, safety, and occupation requirements',
                    type: 2,
                    urls: null,
                    parentId: '76d03cd3-c5f2-450e-8280-63ee89877835',
                    createdAt: 1711596523,
                    deletedAt: null,
                    updatedAt: 1718792307,
                    categoryId: 'd716e43e-7eb7-48c4-a475-98a7cbbdc830',
                    description: null,
                    translation: {
                      en: 'Accommodation does not comply with health, safety, and occupation requirements',
                      ur: 'Accommodation does not comply with health, safety, and occupation requirements Urdu',
                    },
                    riskSeverity: 3,
                  },
                },
                {
                  data: [
                    {
                      note: 'Corrective Action Plan assigned by thuy phan',
                      risk: {
                        level: 'No weight',
                        score: 0,
                      },
                      capId: '639d867e-4892-4fd9-826b-ae47ceea31a5',
                      roleId: null,
                      source: 'CAP',
                      createdAt: 1718333151,
                      isIndirect: false,
                    },
                    {
                      note: 'adasdasd',
                      risk: {
                        level: 'High',
                        score: 10,
                      },
                      roleId: null,
                      source: 'Admin',
                      createdAt: 1718081233,
                      isIndirect: false,
                    },
                  ],
                  risk: {
                    level: 'High',
                    score: 10,
                  },
                  subIndicator: {
                    id: '73a7069a-6f60-4b6d-a4ae-0e2720923caa',
                    icon: null,
                    name: 'Alternate forms of punishment (depriation of food, water, sleep)',
                    type: 2,
                    urls: null,
                    parentId: '76d03cd3-c5f2-450e-8280-63ee89877835',
                    createdAt: 1711596523,
                    deletedAt: null,
                    updatedAt: 1718792307,
                    categoryId: 'd716e43e-7eb7-48c4-a475-98a7cbbdc830',
                    description: null,
                    translation: {
                      en: 'Alternate forms of punishment (depriation of food, water, sleep)',
                      ur: 'Alternate forms of punishment (depriation of food, water, sleep) Urdu',
                    },
                    riskSeverity: 5,
                  },
                },
                {
                  data: [
                    {
                      note: 'thuy add 6/6',
                      risk: {
                        level: 'High',
                        score: 9,
                      },
                      roleId: '62660fc3-4b32-4e7d-b487-59b83b3ad973',
                      source: 'AUDITOR',
                      createdAt: 1717661739,
                      isIndirect: false,
                    },
                    {
                      note: 'aaaa',
                      risk: {
                        level: 'High',
                        score: 9,
                      },
                      roleId: null,
                      source: 'Admin',
                      createdAt: 1711617577,
                      isIndirect: false,
                    },
                  ],
                  risk: {
                    level: 'High',
                    score: 9,
                  },
                  subIndicator: {
                    id: '1a3c841f-0c2e-4510-b2f3-a9a053620dc4',
                    icon: null,
                    name: 'Extra work for breaching labor discipline',
                    type: 2,
                    urls: null,
                    parentId: '76d03cd3-c5f2-450e-8280-63ee89877835',
                    createdAt: 1711596523,
                    deletedAt: null,
                    updatedAt: 1718792307,
                    categoryId: 'd716e43e-7eb7-48c4-a475-98a7cbbdc830',
                    description: null,
                    translation: {
                      en: 'Extra work for breaching labor discipline',
                      ur: 'لیبر ڈسپلن کی خلاف ورزی کے لیے اضافی کام',
                    },
                    riskSeverity: 3,
                  },
                },
              ],
            },
            {
              risk: {
                level: 'Medium',
                score: 4,
              },
              indicator: {
                id: '959a59a1-a90c-4093-9d19-f239dc003b5a',
                icon: null,
                name: 'Debt bondage',
                type: 1,
                urls: null,
                category: {
                  id: 'd716e43e-7eb7-48c4-a475-98a7cbbdc830',
                  icon: 'Abusive working and living conditions',
                  name: 'Labor',
                  type: 3,
                  urls: null,
                  parentId: null,
                  createdAt: 1711596523,
                  deletedAt: null,
                  updatedAt: 1718853151,
                  categoryId: null,
                  description: null,
                  translation: {
                    en: 'Labor',
                  },
                  riskSeverity: 1,
                },
                parentId: null,
                createdAt: 1711596523,
                deletedAt: null,
                updatedAt: 1718792307,
                categoryId: 'd716e43e-7eb7-48c4-a475-98a7cbbdc830',
                description: null,
                translation: {
                  en: 'Debt bondage',
                },
                riskSeverity: 1,
              },
              subIndicatorRiskData: [
                {
                  data: [
                    {
                      note: 'adasdasd',
                      risk: {
                        level: 'Medium',
                        score: 4,
                      },
                      roleId: null,
                      source: 'Admin',
                      createdAt: 1718081233,
                      isIndirect: false,
                    },
                  ],
                  risk: {
                    level: 'Medium',
                    score: 4,
                  },
                  subIndicator: {
                    id: '3f659777-d9f3-4d53-bab9-62eb1b00190c',
                    icon: null,
                    name: 'Forced to work for indeterminate period in order to repay outstanding debt or wage advances',
                    type: 2,
                    urls: null,
                    parentId: '959a59a1-a90c-4093-9d19-f239dc003b5a',
                    createdAt: 1711596523,
                    deletedAt: null,
                    updatedAt: 1718792307,
                    categoryId: 'd716e43e-7eb7-48c4-a475-98a7cbbdc830',
                    description: null,
                    translation: {
                      en: 'Forced to work for indeterminate period in order to repay outstanding debt or wage advances',
                    },
                    riskSeverity: 4,
                  },
                },
              ],
            },
            {
              risk: {
                level: 'Medium',
                score: 5.63,
              },
              indicator: {
                id: 'f460a43f-ece2-441e-8c8d-c5dc88febaa8',
                icon: null,
                name: 'Forced Labor',
                type: 1,
                urls: null,
                category: {
                  id: 'd716e43e-7eb7-48c4-a475-98a7cbbdc830',
                  icon: 'Abusive working and living conditions',
                  name: 'Labor',
                  type: 3,
                  urls: null,
                  parentId: null,
                  createdAt: 1711596523,
                  deletedAt: null,
                  updatedAt: 1718853151,
                  categoryId: null,
                  description: null,
                  translation: {
                    en: 'Labor',
                  },
                  riskSeverity: 1,
                },
                parentId: null,
                createdAt: 1711596523,
                deletedAt: null,
                updatedAt: 1718792307,
                categoryId: 'd716e43e-7eb7-48c4-a475-98a7cbbdc830',
                description: null,
                translation: {
                  en: 'Forced Labor',
                  ur: 'جبری مشقت',
                },
                riskSeverity: 1,
              },
              subIndicatorRiskData: [
                {
                  data: [
                    {
                      note: 'Corrective Action Plan assigned by thuy phan',
                      risk: {
                        level: 'No weight',
                        score: 0,
                      },
                      capId: 'f7b00a0e-a556-4411-a502-7b4ea20d223d',
                      roleId: null,
                      source: 'CAP',
                      createdAt: 1719475604,
                      isIndirect: false,
                    },
                    {
                      note: 'Corrective Action Plan assigned by thuy phan',
                      risk: {
                        level: 'No weight',
                        score: 0,
                      },
                      capId: '462b9ffd-c06a-4974-9340-176873839753',
                      roleId: null,
                      source: 'CAP',
                      createdAt: 1719475565,
                      isIndirect: false,
                    },
                    {
                      note: 'Corrective Action Plan assigned by thuy phan',
                      risk: {
                        level: 'No weight',
                        score: 0,
                      },
                      capId: 'c90efa28-e2d1-4c6a-b5a7-8a40c0b03bdd',
                      roleId: null,
                      source: 'CAP',
                      createdAt: 1719475040,
                      isIndirect: false,
                    },
                    {
                      note: 'Evidence accepted of completion of corrective actions.<strong> New risk level assigned: Medium risk </strong>',
                      risk: {
                        level: 'Medium',
                        score: 5.63,
                      },
                      capId: '1e258b41-3f07-4108-9a6e-6706ef6e83af',
                      roleId: null,
                      source: 'CAP',
                      createdAt: 1718592514,
                      isIndirect: false,
                    },
                    {
                      note: 'Corrective Action Plan assigned by thuy phan',
                      risk: {
                        level: 'No weight',
                        score: 0,
                      },
                      capId: '20d0426f-38ec-421d-ac99-b76ff6b44306',
                      roleId: null,
                      source: 'CAP',
                      createdAt: 1718336911,
                      isIndirect: false,
                    },
                    {
                      note: 'Corrective Action Plan assigned by thuy phan',
                      risk: {
                        level: 'No weight',
                        score: 0,
                      },
                      capId: '7d9fd5da-053e-41c9-897f-0f6315c52498',
                      roleId: null,
                      source: 'CAP',
                      createdAt: 1718336492,
                      isIndirect: false,
                    },
                    {
                      note: 'Evidence accepted of completion of corrective actions.<strong> New risk level assigned: Medium risk </strong>',
                      risk: {
                        level: 'Medium',
                        score: 5.63,
                      },
                      capId: '3357c647-4f0f-4443-9490-0439afa91fb7',
                      roleId: null,
                      source: 'CAP',
                      createdAt: 1718176632,
                      isIndirect: false,
                    },
                    {
                      note: 'Corrective Action Plan assigned by thuy phan',
                      risk: {
                        level: 'No weight',
                        score: 0,
                      },
                      capId: 'b1953bc2-16cd-4256-b2f1-d6bb0e8031ef',
                      roleId: null,
                      source: 'CAP',
                      createdAt: 1718176595,
                      isIndirect: false,
                    },
                    {
                      note: 'Evidence accepted of completion of corrective actions.<strong> New risk level assigned: Extreme risk </strong>',
                      risk: {
                        level: 'Extreme',
                        score: 13.129999999999999,
                      },
                      capId: '06939ca8-868a-4ddf-a838-3247605ef170',
                      roleId: null,
                      source: 'CAP',
                      createdAt: 1718176506,
                      isIndirect: false,
                    },
                    {
                      note: 'Corrective Action Plan assigned by thuy phan',
                      risk: {
                        level: 'No weight',
                        score: 0,
                      },
                      capId: '749a729a-901b-45bd-8340-62da9523edc8',
                      roleId: null,
                      source: 'CAP',
                      createdAt: 1718176467,
                      isIndirect: false,
                    },
                    {
                      note: 'Evidence accepted of completion of corrective actions.<strong> New risk level assigned: Medium risk </strong>',
                      risk: {
                        level: 'Medium',
                        score: 5.63,
                      },
                      capId: '066a6509-44de-4977-9179-a1876801f948',
                      roleId: null,
                      source: 'CAP',
                      createdAt: 1718176097,
                      isIndirect: false,
                    },
                    {
                      note: 'Corrective Action Plan assigned by thuy phan',
                      risk: {
                        level: 'No weight',
                        score: 0,
                      },
                      capId: 'b60f7e89-e043-498a-92d8-83af854ffd51',
                      roleId: null,
                      source: 'CAP',
                      createdAt: 1718176054,
                      isIndirect: false,
                    },
                    {
                      note: 'Evidence accepted of completion of corrective actions.<strong> New risk level assigned: Low risk </strong>',
                      risk: {
                        level: 'Low',
                        score: 2.375,
                      },
                      capId: '7d8cab30-fd0f-4bf2-8157-11b2b2282362',
                      roleId: null,
                      source: 'CAP',
                      createdAt: 1718175989,
                      isIndirect: false,
                    },
                    {
                      note: 'Corrective Action Plan assigned by thuy phan',
                      risk: {
                        level: 'No weight',
                        score: 0,
                      },
                      capId: '1e38520e-7004-45ae-a81b-2cbfd2c87566',
                      roleId: null,
                      source: 'CAP',
                      createdAt: 1718175935,
                      isIndirect: false,
                    },
                    {
                      note: 'thuy add report 7.5',
                      risk: {
                        level: 'Extreme',
                        score: 15,
                      },
                      roleId: null,
                      source: 'Admin',
                      createdAt: 1715057808,
                      isIndirect: false,
                    },
                  ],
                  risk: {
                    level: 'Medium',
                    score: 5.63,
                  },
                  subIndicator: {
                    id: 'bcac1368-3bd8-4391-9ca4-c239bb452e72',
                    icon: null,
                    name: 'Goods produced with forced labor (ILAB List of Goods)',
                    type: 2,
                    urls: null,
                    parentId: 'f460a43f-ece2-441e-8c8d-c5dc88febaa8',
                    createdAt: 1711596523,
                    deletedAt: null,
                    updatedAt: 1718792307,
                    categoryId: 'd716e43e-7eb7-48c4-a475-98a7cbbdc830',
                    description: null,
                    translation: {
                      en: 'Goods produced with forced labor (ILAB List of Goods)',
                      ur: 'جبری مشقت کے ساتھ تیار کردہ سامان (آلات کی ILAB فہرست)',
                    },
                    riskSeverity: 5,
                  },
                },
              ],
            },
            {
              risk: {
                level: 'Low',
                score: 3,
              },
              indicator: {
                id: 'f0aba53b-ee7c-4c88-8290-b3be20f6d243',
                icon: null,
                name: 'Child labor',
                type: 1,
                urls: null,
                category: {
                  id: 'd716e43e-7eb7-48c4-a475-98a7cbbdc830',
                  icon: 'Abusive working and living conditions',
                  name: 'Labor',
                  type: 3,
                  urls: null,
                  parentId: null,
                  createdAt: 1711596523,
                  deletedAt: null,
                  updatedAt: 1718853151,
                  categoryId: null,
                  description: null,
                  translation: {
                    en: 'Labor',
                  },
                  riskSeverity: 1,
                },
                parentId: null,
                createdAt: 1711596523,
                deletedAt: null,
                updatedAt: 1718792307,
                categoryId: 'd716e43e-7eb7-48c4-a475-98a7cbbdc830',
                description: null,
                translation: {
                  en: 'Child labor',
                },
                riskSeverity: 1,
              },
              subIndicatorRiskData: [
                {
                  data: [
                    {
                      note: 'Corrective Action Plan assigned by thuy abcd brand',
                      risk: {
                        level: 'No weight',
                        score: 0,
                      },
                      capId: '7a4069e3-f287-4a30-96d8-96d86d486363',
                      roleId: null,
                      source: 'CAP',
                      createdAt: 1719563343,
                      isIndirect: false,
                    },
                    {
                      note: 'Gloves',
                      risk: {
                        level: 'Low',
                        score: 3,
                      },
                      roleId: null,
                      source: 'Product risk listings',
                      createdAt: 1662687784,
                    },
                  ],
                  risk: {
                    level: 'Low',
                    score: 3,
                  },
                  subIndicator: {
                    id: 'a877d4d9-6a03-4a0d-9679-f8e242355a50',
                    icon: null,
                    name: 'Children working overtime',
                    type: 2,
                    urls: null,
                    parentId: 'f0aba53b-ee7c-4c88-8290-b3be20f6d243',
                    createdAt: 1715240896,
                    deletedAt: null,
                    updatedAt: 1718792307,
                    categoryId: 'd716e43e-7eb7-48c4-a475-98a7cbbdc830',
                    description: null,
                    translation: {
                      en: 'Children working overtime',
                    },
                    riskSeverity: 3,
                  },
                },
              ],
            },
          ],
        },
        {
          risk: {
            level: 'Medium',
            score: 6.307272727272727,
          },
          category: {
            id: '3cbe8252-64bc-4c30-9fb3-36337a6a68e2',
            icon: 'Good health and well-being',
            name: 'Occupational Safety & Health',
            type: 3,
            urls: null,
            parentId: null,
            createdAt: 1711596523,
            deletedAt: null,
            updatedAt: 1719215634,
            categoryId: null,
            description: null,
            translation: {
              en: 'Occupational Safety & Health',
            },
            riskSeverity: 1,
          },
          sourceRiskData: [
            {
              risk: {
                level: 'High',
                score: 9.379999999999999,
              },
              source: 'CAP',
            },
            {
              risk: {
                level: 'Medium',
                score: 6,
              },
              source: 'Admin',
            },
          ],
          indicatorRiskData: [
            {
              risk: {
                level: 'High',
                score: 9.379999999999999,
              },
              indicator: {
                id: '5f4b7a4e-7533-476c-afed-6678f3f89457',
                icon: null,
                name: 'Worker protection',
                type: 1,
                urls: null,
                category: {
                  id: '3cbe8252-64bc-4c30-9fb3-36337a6a68e2',
                  icon: 'Good health and well-being',
                  name: 'Occupational Safety & Health',
                  type: 3,
                  urls: null,
                  parentId: null,
                  createdAt: 1711596523,
                  deletedAt: null,
                  updatedAt: 1719215634,
                  categoryId: null,
                  description: null,
                  translation: {
                    en: 'Occupational Safety & Health',
                  },
                  riskSeverity: 1,
                },
                parentId: null,
                createdAt: 1711596523,
                deletedAt: null,
                updatedAt: 1718792307,
                categoryId: '3cbe8252-64bc-4c30-9fb3-36337a6a68e2',
                description: null,
                translation: {
                  en: 'Worker protection',
                },
                riskSeverity: 1,
              },
              subIndicatorRiskData: [
                {
                  data: [
                    {
                      note: 'Evidence accepted of completion of corrective actions.<strong> New risk level assigned: High risk </strong>',
                      risk: {
                        level: 'High',
                        score: 9.379999999999999,
                      },
                      capId: '89049c01-cf68-4900-9fb0-8f04d764d0b6',
                      roleId: null,
                      source: 'CAP',
                      createdAt: 1718188112,
                      isIndirect: false,
                    },
                    {
                      note: 'Corrective Action Plan assigned by thuy phan',
                      risk: {
                        level: 'No weight',
                        score: 0,
                      },
                      capId: '1b29a540-0a1f-4824-ba41-339ccdbd53c0',
                      roleId: null,
                      source: 'CAP',
                      createdAt: 1718188045,
                      isIndirect: false,
                    },
                    {
                      note: 'Evidence accepted of completion of corrective actions.<strong> New risk level assigned: Low risk </strong>',
                      risk: {
                        level: 'Low',
                        score: 2.375,
                      },
                      capId: '9397812e-600b-4ef2-9508-d00ff5eb7cca',
                      roleId: null,
                      source: 'CAP',
                      createdAt: 1718187927,
                      isIndirect: false,
                    },
                    {
                      note: 'Corrective Action Plan assigned by thuy phan',
                      risk: {
                        level: 'No weight',
                        score: 0,
                      },
                      capId: '1fd51aa0-c7ca-4033-aacb-0676838f912b',
                      roleId: null,
                      source: 'CAP',
                      createdAt: 1718187641,
                      isIndirect: false,
                    },
                    {
                      note: 'njjj',
                      risk: {
                        level: 'High',
                        score: 8,
                      },
                      roleId: null,
                      source: 'Admin',
                      createdAt: 1718082136,
                      isIndirect: false,
                    },
                  ],
                  risk: {
                    level: 'High',
                    score: 9.379999999999999,
                  },
                  subIndicator: {
                    id: '13d98501-b5fe-42c1-a53f-45bab6281032',
                    icon: null,
                    name: 'Inadequate provision of PPE (e.g dust masks, ear protection)',
                    type: 2,
                    urls: null,
                    parentId: '5f4b7a4e-7533-476c-afed-6678f3f89457',
                    createdAt: 1711596523,
                    deletedAt: null,
                    updatedAt: 1718792307,
                    categoryId: '3cbe8252-64bc-4c30-9fb3-36337a6a68e2',
                    description: null,
                    translation: {
                      en: 'Inadequate provision of PPE (e.g dust masks, ear protection)',
                    },
                    riskSeverity: 4,
                  },
                },
              ],
            },
            {
              risk: {
                level: 'Medium',
                score: 6,
              },
              indicator: {
                id: '61d83613-f18c-4153-9c24-be4aebdae598',
                icon: null,
                name: 'Chemicals and hazardous material',
                type: 1,
                urls: null,
                category: {
                  id: '3cbe8252-64bc-4c30-9fb3-36337a6a68e2',
                  icon: 'Good health and well-being',
                  name: 'Occupational Safety & Health',
                  type: 3,
                  urls: null,
                  parentId: null,
                  createdAt: 1711596523,
                  deletedAt: null,
                  updatedAt: 1719215634,
                  categoryId: null,
                  description: null,
                  translation: {
                    en: 'Occupational Safety & Health',
                  },
                  riskSeverity: 1,
                },
                parentId: null,
                createdAt: 1711596523,
                deletedAt: null,
                updatedAt: 1718792307,
                categoryId: '3cbe8252-64bc-4c30-9fb3-36337a6a68e2',
                description: null,
                translation: {
                  en: 'Chemicals and hazardous material',
                },
                riskSeverity: 1,
              },
              subIndicatorRiskData: [
                {
                  data: [
                    {
                      note: 'Corrective Action Plan assigned by thuy phan',
                      risk: {
                        level: 'No weight',
                        score: 0,
                      },
                      capId: '50846dbe-340e-4015-9aac-84b4a5d0a1d4',
                      roleId: null,
                      source: 'CAP',
                      createdAt: 1719366074,
                      isIndirect: false,
                    },
                    {
                      note: 'adasdasd',
                      risk: {
                        level: 'Medium',
                        score: 6,
                      },
                      roleId: null,
                      source: 'Admin',
                      createdAt: 1718081233,
                      isIndirect: false,
                    },
                  ],
                  risk: {
                    level: 'Medium',
                    score: 6,
                  },
                  subIndicator: {
                    id: '046b8443-84e1-4b37-9731-24b99dd3eddd',
                    icon: null,
                    name: 'Inadequate training for use of chemicals and hazardous substances',
                    type: 2,
                    urls: null,
                    parentId: '61d83613-f18c-4153-9c24-be4aebdae598',
                    createdAt: 1711596523,
                    deletedAt: null,
                    updatedAt: 1718792307,
                    categoryId: '3cbe8252-64bc-4c30-9fb3-36337a6a68e2',
                    description: null,
                    translation: {
                      en: 'Inadequate training for use of chemicals and hazardous substances',
                    },
                    riskSeverity: 3,
                  },
                },
              ],
            },
          ],
        },
      ],
      countryRisk: {
        level: 'High',
        score: 56,
      },
      overallRisk: {
        level: 'High',
        score: 7.7689385474860355,
      },
    },
    type: {
      id: 'e6be1a55-26f0-4fc9-ac27-6cc51f0dc0e5',
      createdAt: 1686198227,
      updatedAt: 1721185075,
      name: 'GINNER',
      type: 'Producer',
      chainOfCustody: 'Product Segregation',
      isRawMaterialExtractor: false,
      seasonStartDate: null,
      seasonDuration: null,
      icon: null,
    },
    orderSupplierId: 'a7791cd6-72d3-4963-aeae-c59bdd7364e5',
    isRoot: true,
    label: 'Ginner',
    targets: [],
  },
  {
    orderSupplierId: '684be6d0-2084-44ba-b59f-4d59d1e4e524',
    isRoot: false,
    label: 'Non-participating Farm',
    targets: ['a7791cd6-72d3-4963-aeae-c59bdd7364e5'],
  },
  {
    id: '361bebdc-2721-4ce1-8818-e0ca7facb6db',
    name: 'Mitho Lakhan-092',
    riskData: {
      data: [
        {
          risk: {
            level: 'Medium',
            score: 5.63,
          },
          category: {
            id: 'd716e43e-7eb7-48c4-a475-98a7cbbdc830',
            icon: 'Abusive working and living conditions',
            name: 'Labor',
            type: 3,
            parentId: null,
            createdAt: 1711596523,
            deletedAt: null,
            updatedAt: 1718853151,
            categoryId: null,
            translation: {
              en: 'Labor',
            },
            riskSeverity: 1,
          },
          sourceRiskData: [
            {
              risk: {
                level: 'Medium',
                score: 5.63,
              },
              source: 'CAP',
            },
          ],
          indicatorRiskData: [
            {
              risk: {
                level: 'Medium',
                score: 5.63,
              },
              indicator: {
                id: 'f460a43f-ece2-441e-8c8d-c5dc88febaa8',
                icon: null,
                name: 'Forced Labor',
                type: 1,
                category: {
                  id: 'd716e43e-7eb7-48c4-a475-98a7cbbdc830',
                  icon: 'Abusive working and living conditions',
                  name: 'Labor',
                  type: 3,
                  parentId: null,
                  createdAt: 1711596523,
                  deletedAt: null,
                  updatedAt: 1718853151,
                  categoryId: null,
                  translation: {
                    en: 'Labor',
                  },
                  riskSeverity: 1,
                },
                parentId: null,
                createdAt: 1711596523,
                deletedAt: null,
                updatedAt: 1718792307,
                categoryId: 'd716e43e-7eb7-48c4-a475-98a7cbbdc830',
                translation: {
                  en: 'Forced Labor',
                  ur: 'جبری مشقت',
                },
                riskSeverity: 1,
              },
              subIndicatorRiskData: [
                {
                  data: [
                    {
                      note: 'Evidence accepted of completion of corrective actions.<strong> New risk level assigned: Medium risk </strong>',
                      risk: {
                        level: 'Medium',
                        score: 5.63,
                      },
                      capId: '1e258b41-3f07-4108-9a6e-6706ef6e83af',
                      roleId: null,
                      source: 'CAP',
                      createdAt: 1718592514,
                      isIndirect: false,
                    },
                    {
                      note: 'Corrective Action Plan assigned by thuy phan',
                      risk: {
                        level: 'No weight',
                        score: 0,
                      },
                      capId: '20d0426f-38ec-421d-ac99-b76ff6b44306',
                      roleId: null,
                      source: 'CAP',
                      createdAt: 1718336911,
                      isIndirect: false,
                    },
                    {
                      note: 'Corrective Action Plan assigned by thuy phan',
                      risk: {
                        level: 'No weight',
                        score: 0,
                      },
                      capId: '7d9fd5da-053e-41c9-897f-0f6315c52498',
                      roleId: null,
                      source: 'CAP',
                      createdAt: 1718336492,
                      isIndirect: false,
                    },
                    {
                      note: 'Evidence accepted of completion of corrective actions.<strong> New risk level assigned: Medium risk </strong>',
                      risk: {
                        level: 'Medium',
                        score: 5.63,
                      },
                      capId: '3357c647-4f0f-4443-9490-0439afa91fb7',
                      roleId: null,
                      source: 'CAP',
                      createdAt: 1718176632,
                      isIndirect: false,
                    },
                    {
                      note: 'Corrective Action Plan assigned by thuy phan',
                      risk: {
                        level: 'No weight',
                        score: 0,
                      },
                      capId: 'b1953bc2-16cd-4256-b2f1-d6bb0e8031ef',
                      roleId: null,
                      source: 'CAP',
                      createdAt: 1718176595,
                      isIndirect: false,
                    },
                    {
                      note: 'Evidence accepted of completion of corrective actions.<strong> New risk level assigned: Extreme risk </strong>',
                      risk: {
                        level: 'Extreme',
                        score: 13.129999999999999,
                      },
                      capId: '06939ca8-868a-4ddf-a838-3247605ef170',
                      roleId: null,
                      source: 'CAP',
                      createdAt: 1718176506,
                      isIndirect: false,
                    },
                    {
                      note: 'Corrective Action Plan assigned by thuy phan',
                      risk: {
                        level: 'No weight',
                        score: 0,
                      },
                      capId: '749a729a-901b-45bd-8340-62da9523edc8',
                      roleId: null,
                      source: 'CAP',
                      createdAt: 1718176467,
                      isIndirect: false,
                    },
                    {
                      note: 'Evidence accepted of completion of corrective actions.<strong> New risk level assigned: Medium risk </strong>',
                      risk: {
                        level: 'Medium',
                        score: 5.63,
                      },
                      capId: '066a6509-44de-4977-9179-a1876801f948',
                      roleId: null,
                      source: 'CAP',
                      createdAt: 1718176097,
                      isIndirect: false,
                    },
                    {
                      note: 'Corrective Action Plan assigned by thuy phan',
                      risk: {
                        level: 'No weight',
                        score: 0,
                      },
                      capId: 'b60f7e89-e043-498a-92d8-83af854ffd51',
                      roleId: null,
                      source: 'CAP',
                      createdAt: 1718176054,
                      isIndirect: false,
                    },
                    {
                      note: 'Evidence accepted of completion of corrective actions.<strong> New risk level assigned: Low risk </strong>',
                      risk: {
                        level: 'Low',
                        score: 2.375,
                      },
                      capId: '7d8cab30-fd0f-4bf2-8157-11b2b2282362',
                      roleId: null,
                      source: 'CAP',
                      createdAt: 1718175989,
                      isIndirect: false,
                    },
                    {
                      note: 'Corrective Action Plan assigned by thuy phan',
                      risk: {
                        level: 'No weight',
                        score: 0,
                      },
                      capId: '1e38520e-7004-45ae-a81b-2cbfd2c87566',
                      roleId: null,
                      source: 'CAP',
                      createdAt: 1718175935,
                      isIndirect: false,
                    },
                    {
                      note: 'Evidence accepted of completion of corrective actions.<strong> New risk level assigned: High risk </strong>',
                      risk: {
                        level: 'High',
                        score: 9.379999999999999,
                      },
                      capId: '248fc816-5146-4594-9f73-b1d455b3808e',
                      roleId: null,
                      source: 'CAP',
                      createdAt: 1718090722,
                      isIndirect: false,
                    },
                    {
                      note: 'rwewrwre',
                      risk: {
                        level: 'No weight',
                        score: 0,
                      },
                      capId: 'c001356b-a96c-4db7-9b29-db9ecdb62425',
                      roleId: null,
                      source: 'CAP',
                      createdAt: 1718090683,
                      isIndirect: false,
                    },
                    {
                      note: 'Evidence accepted of completion of corrective actions.<strong> New risk level assigned: Low risk </strong>',
                      risk: {
                        level: 'Low',
                        score: 2.375,
                      },
                      capId: '1303b6e1-af59-4b1e-baac-e1f90a67d955',
                      roleId: null,
                      source: 'CAP',
                      createdAt: 1718078168,
                      isIndirect: false,
                    },
                    {
                      note: 'tautest',
                      risk: {
                        level: 'No weight',
                        score: 0,
                      },
                      capId: 'bfb431b5-aeb6-40f3-bf4c-9d097e10a8e8',
                      roleId: null,
                      source: 'CAP',
                      createdAt: 1718006795,
                      isIndirect: false,
                    },
                    {
                      note: 'tesst',
                      risk: {
                        level: 'No weight',
                        score: 0,
                      },
                      capId: '6f9cbebc-9f60-4923-a9f6-e3db88e4602f',
                      roleId: null,
                      source: 'CAP',
                      createdAt: 1717470018,
                      isIndirect: false,
                    },
                    {
                      note: 'thuy test 4/6',
                      risk: {
                        level: 'No weight',
                        score: 0,
                      },
                      capId: '79ce7071-4ce2-4980-8466-7bee923c9391',
                      roleId: null,
                      source: 'CAP',
                      createdAt: 1717468957,
                      isIndirect: false,
                    },
                    {
                      note: 'test1',
                      risk: {
                        level: 'No weight',
                        score: 0,
                      },
                      capId: '4c91c740-f8e9-4463-88ee-9ad4a8d75ef8',
                      roleId: null,
                      source: 'CAP',
                      createdAt: 1717043240,
                      isIndirect: false,
                    },
                    {
                      note: '123123',
                      risk: {
                        level: 'No weight',
                        score: 0,
                      },
                      capId: '3690a492-3518-43ff-accf-547ba7d5c333',
                      roleId: null,
                      source: 'CAP',
                      createdAt: 1716190370,
                      isIndirect: false,
                    },
                    {
                      note: '22112',
                      risk: {
                        level: 'No weight',
                        score: 0,
                      },
                      capId: '2e2086eb-42e0-4f2e-92ce-04005393912b',
                      roleId: null,
                      source: 'CAP',
                      createdAt: 1716127857,
                      isIndirect: false,
                    },
                    {
                      note: '123123',
                      risk: {
                        level: 'No weight',
                        score: 0,
                      },
                      capId: '745f66b3-499d-4bb9-8ba5-71e8fc147cf2',
                      roleId: null,
                      source: 'CAP',
                      createdAt: 1716127697,
                      isIndirect: false,
                    },
                    {
                      note: 'hurure',
                      risk: {
                        level: 'Extreme',
                        score: 15,
                      },
                      roleId: null,
                      source: 'Admin',
                      createdAt: 1711617643,
                      isIndirect: false,
                    },
                  ],
                  risk: {
                    level: 'Medium',
                    score: 5.63,
                  },
                  subIndicator: {
                    id: 'bcac1368-3bd8-4391-9ca4-c239bb452e72',
                    icon: null,
                    name: 'Goods produced with forced labor (ILAB List of Goods)',
                    type: 2,
                    parentId: 'f460a43f-ece2-441e-8c8d-c5dc88febaa8',
                    createdAt: 1711596523,
                    deletedAt: null,
                    updatedAt: 1718792307,
                    categoryId: 'd716e43e-7eb7-48c4-a475-98a7cbbdc830',
                    translation: {
                      en: 'Goods produced with forced labor (ILAB List of Goods)',
                      ur: 'جبری مشقت کے ساتھ تیار کردہ سامان (آلات کی ILAB فہرست)',
                    },
                    riskSeverity: 5,
                  },
                },
              ],
            },
          ],
        },
      ],
      countryRisk: {
        level: 'High',
        score: 71,
      },
      overallRisk: {
        level: 'Medium',
        score: 5.63,
      },
    },
    type: {
      id: 'ca7c964c-0b7c-4f48-aa2a-175a97139688',
      createdAt: 1686198227,
      updatedAt: 1708591218,
      name: 'FARM',
      type: 'Producer',
      chainOfCustody: null,
      isRawMaterialExtractor: true,
      seasonStartDate: '02/01/2022',
      seasonDuration: 4,
      icon: null,
    },
    orderSupplierId: '23d6090b-bfbc-4af7-96f2-f87c2b0a34fe',
    isRoot: false,
    label: 'Farm',
    targets: [
      'a7791cd6-72d3-4963-aeae-c59bdd7364e5',
      '0c22f009-4424-40a6-949f-eb3e1df70a93',
    ],
  },
  {
    id: '2a7e7fc7-16c3-4912-80e5-d71c868d6905',
    name: 'add broker thuy',
    riskData: {
      data: [],
      countryRisk: {
        level: 'High',
        score: 75,
      },
      overallRisk: {
        level: 'Low',
        score: 0,
      },
    },
    type: {
      id: '8f356b17-cdf7-4ff9-8cc5-8f41041b3fcb',
      createdAt: 1686198227,
      updatedAt: 1686198227,
      name: 'BROKER',
      type: 'Producer',
      chainOfCustody: 'Product Segregation',
      isRawMaterialExtractor: null,
      seasonStartDate: null,
      seasonDuration: null,
      icon: null,
    },
    orderSupplierId: '0c22f009-4424-40a6-949f-eb3e1df70a93',
    isRoot: false,
    label: 'Broker',
    targets: ['a7791cd6-72d3-4963-aeae-c59bdd7364e5'],
  },
  {
    id: '2ad3da92-be2a-46eb-861b-a950dac6d320',
    name: 'Farm 4',
    riskData: {
      data: [],
      countryRisk: {
        level: 'High',
        score: 71,
      },
      overallRisk: {
        level: 'No weight',
        score: 0,
      },
    },
    type: {
      id: 'ca7c964c-0b7c-4f48-aa2a-175a97139688',
      createdAt: 1686198227,
      updatedAt: 1708591218,
      name: 'FARM',
      type: 'Producer',
      chainOfCustody: null,
      isRawMaterialExtractor: true,
      seasonStartDate: '02/01/2022',
      seasonDuration: 4,
      icon: null,
    },
    orderSupplierId: '57bf9e64-a6ca-498e-bb8f-7dcbb4698d18',
    isRoot: false,
    label: 'Farm',
    targets: ['0c22f009-4424-40a6-949f-eb3e1df70a93'],
  },
] as any;
